// <auto-generated />
using System;
using API_HotelManagement.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_HotelManagement.Data.Migrations
{
    [DbContext(typeof(HtDbContext))]
    [Migration("20240116215507_InitHotelManagementDb_V1")]
    partial class InitHotelManagementDb_V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entity.Ht_Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ht_Test");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d749d28-3405-45f7-8fd1-fdae05a0dea9"),
                            CreateBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            CreateDate = new DateTime(2024, 1, 17, 4, 55, 6, 939, DateTimeKind.Local).AddTicks(7928),
                            ModifiedBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            ModifiedDate = new DateTime(2024, 1, 17, 4, 55, 6, 939, DateTimeKind.Local).AddTicks(7947),
                            Name = "hello 1"
                        },
                        new
                        {
                            Id = new Guid("801f03d6-5bb6-44b1-9460-9cdf4617aaf9"),
                            CreateBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            CreateDate = new DateTime(2024, 1, 17, 4, 55, 6, 939, DateTimeKind.Local).AddTicks(7949),
                            ModifiedBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            ModifiedDate = new DateTime(2024, 1, 17, 4, 55, 6, 939, DateTimeKind.Local).AddTicks(7951),
                            Name = "hello 2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
