// <auto-generated />
using System;
using API_HotelManagement.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_HotelManagement.Data.Migrations
{
    [DbContext(typeof(HtDbContext))]
    partial class HtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entity.ht_Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ht_Test");

                    b.HasData(
                        new
                        {
                            Id = new Guid("9d749d28-3405-45f7-8fd1-fdae05a0dea9"),
                            CreateBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            CreateDate = new DateTime(2024, 1, 17, 13, 54, 15, 754, DateTimeKind.Local).AddTicks(8816),
                            ModifiedBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 54, 15, 754, DateTimeKind.Local).AddTicks(8837),
                            Name = "hello 1"
                        },
                        new
                        {
                            Id = new Guid("801f03d6-5bb6-44b1-9460-9cdf4617aaf9"),
                            CreateBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            CreateDate = new DateTime(2024, 1, 17, 13, 54, 15, 754, DateTimeKind.Local).AddTicks(8840),
                            ModifiedBy = new Guid("7c67e72e-e773-447f-9f3e-9c3a480be605"),
                            ModifiedDate = new DateTime(2024, 1, 17, 13, 54, 15, 754, DateTimeKind.Local).AddTicks(8841),
                            Name = "hello 2"
                        });
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entity.ht_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ht_User");
                });
#pragma warning restore 612, 618
        }
    }
}
