// <auto-generated />
using System;
using API_HotelManagement.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_HotelManagement.Data.Migrations
{
    [DbContext(typeof(HtDbContext))]
    partial class HtDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_CategoryRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ht_CategoryRoom");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_CategoryService", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CategoryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.ToTable("ht_CategoryService");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Hotel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HotelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ht_Hotel");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("Text");

                    b.HasKey("Id");

                    b.ToTable("ht_Order");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_OrderRoomDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("TimeEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeStart")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("RoomId");

                    b.ToTable("ht_OrderRoomDetail");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_OrderServiceDetail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("OrderTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<Guid?>("ServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ServiceId");

                    b.ToTable("ht_OrderServiceDetail");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HotelId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("HotelId");

                    b.HasIndex("UserId");

                    b.ToTable("ht_Role");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FloorNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RoomName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryRoomId");

                    b.ToTable("ht_Room");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Service", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CategoryServiceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ServiceName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryServiceId");

                    b.ToTable("ht_Service");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreateBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("ModifiedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("PasswordUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("ht_User");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_CategoryRoom", b =>
                {
                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_Hotel", "Hotel")
                        .WithMany("ht_CategoryRooms")
                        .HasForeignKey("HotelId")
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_CategoryService", b =>
                {
                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_Hotel", "Hotel")
                        .WithMany("ht_CategoryServices")
                        .HasForeignKey("HotelId")
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_OrderRoomDetail", b =>
                {
                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_Order", "Order")
                        .WithMany("OrderRoomDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_Room", "Room")
                        .WithMany("OrderRoomDetails")
                        .HasForeignKey("RoomId");

                    b.Navigation("Order");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_OrderServiceDetail", b =>
                {
                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_Order", "Order")
                        .WithMany("OrderServiceDetails")
                        .HasForeignKey("OrderId");

                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_Service", "Service")
                        .WithMany("OrderServiceDetails")
                        .HasForeignKey("ServiceId");

                    b.Navigation("Order");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Role", b =>
                {
                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_Hotel", "Hotel")
                        .WithMany("ht_Roles")
                        .HasForeignKey("HotelId")
                        .IsRequired();

                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_User", "User")
                        .WithMany("ht_Roles")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("User");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Room", b =>
                {
                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_CategoryRoom", "CategoryRoom")
                        .WithMany("Rooms")
                        .HasForeignKey("CategoryRoomId");

                    b.Navigation("CategoryRoom");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Service", b =>
                {
                    b.HasOne("API_HotelManagement.Data.Data.Entitys.ht_CategoryService", "CategoryService")
                        .WithMany("ht_Services")
                        .HasForeignKey("CategoryServiceId");

                    b.Navigation("CategoryService");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_CategoryRoom", b =>
                {
                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_CategoryService", b =>
                {
                    b.Navigation("ht_Services");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Hotel", b =>
                {
                    b.Navigation("ht_CategoryRooms");

                    b.Navigation("ht_CategoryServices");

                    b.Navigation("ht_Roles");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Order", b =>
                {
                    b.Navigation("OrderRoomDetails");

                    b.Navigation("OrderServiceDetails");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Room", b =>
                {
                    b.Navigation("OrderRoomDetails");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_Service", b =>
                {
                    b.Navigation("OrderServiceDetails");
                });

            modelBuilder.Entity("API_HotelManagement.Data.Data.Entitys.ht_User", b =>
                {
                    b.Navigation("ht_Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
